services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: mail-dispatcher-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mail_dispatcher_password
      MYSQL_DATABASE: mail_dispatcher
      MYSQL_USER: mail_dispatcher
      MYSQL_PASSWORD: mail_dispatcher_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mail-dispatcher-network

  # 邮件转发系统
  mail-dispatcher:
    build: .
    container_name: mail-dispatcher-app
    restart: unless-stopped
    environment:
      # 数据库配置
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: mail_dispatcher
      DB_PASSWORD: mail_dispatcher_password
      DB_NAME: mail_dispatcher
      DB_CHARSET: utf8mb4
      
      # 服务器配置
      SERVER_PORT: 8080
      SERVER_HOST: 0.0.0.0
      
      # 邮件配置
      MAIL_POLLING_INTERVAL: 300
      MAIL_MAX_RETRY_COUNT: 3
      MAIL_RETRY_INTERVAL: 60
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ./logs:/root/logs
    networks:
      - mail-dispatcher-network

volumes:
  mysql_data:

networks:
  mail-dispatcher-network:
    driver: bridge 